### PR TITLE
refactor: use 'sass' instead of 'node_sass'

### PR DESCRIPTION
**Pull request by cary-smith**
Dart-sass (or just [sass on npm](https://www.npmjs.com/package/sass)) provides a full JavaScript version of sass and will likely be updated sooner than lib-sass if [the documentation](https://sass-lang.com/dart-sass) is correct.  For people that live behind oppressive firewalls that block certain kinds of downloads, this is a lifesaver. 

I have run this version in my local stencil projects without issue, but we also use pretty slim sass functionality (mainly nesting, mixins and variables).

Just offering this as an option should you like to try it over node-sass.

### CODE REVIEW

**Comment by cary-smith** [comment]
We have started moving multiple other projects (non-stencil) to 'sass' with very few hiccups (mainly misuse of `@extend` in a few places). The performance seem comparable and has no binary requirements.

**Comment by vidarc** [comment]
I would love for this PR to get merged. node-sass always seems to cause some sort of issue every month or so due to the need to download and build that binary. and those of us behind corporate proxies have quite a bit of issues working around the install procedure.

**Comment by johnstrickler** [comment]
This would really help eliminate the headache of using node-sass.  Hope to see this merged soon.

**Comment by adamdbradley** [comment]
Yeah I'm a big fan of "no native code or external dependencies". I'll make the update and ship a prerelease to see how it goes. Thanks

**Pull request merged**
