### PR TITLE
fix: 🐛 Allow import OR use to not be breaking

### LINKED ISSUE #43: v1.4.0 breaks mixins included via injectGlobalPaths
Something about the upgrade from v1.3.2 to v1.4.0 has broken the ability to have global mixins declared in `injectGlobalPaths` files accessible to any other `scss` files in the project. 

Here is a minimal reproduction of the issue: https://github.com/nikrolls/stenciljs-sass-globalpaths-repro

```
$ npm start

> stenciljs-sass-globalpaths-repro@0.0.1 start
> stencil build --dev --watch --serve

[34:03.0]  @stencil/core
[34:03.2]  v1.17.4 🏏
[34:07.8]  build, stenciljs-sass-globalpaths-repro, dev mode, started ...
[34:07.9]  transpile started ...
[34:10.2]  transpile finished in 2.30 s
[34:10.2]  copy started ...
[34:10.2]  generate lazy started ...
[34:10.2]  copy finished (0 files) in 39 ms
[34:10.9]  generate lazy finished in 753 ms

[ ERROR ]  sass error: src/global/global.scss:1:72
           Undefined mixin.

      L1:  @include test-mixin;

[34:10.9]  build failed, watching for changes... in 3.12 s
```
However, if you change `@stencil/sass` in `package.json` to `1.3.2`:
```
$ npm upgrade

changed 1 package, and audited 3 packages in 2s

found 0 vulnerabilities
$ npm start

> stenciljs-sass-globalpaths-repro@0.0.1 start
> stencil build --dev --watch --serve

[35:42.3]  @stencil/core
[35:42.5]  v1.17.4 🏏
[35:47.1]  build, stenciljs-sass-globalpaths-repro, dev mode, started ...
[35:47.1]  transpile started ...
[35:49.7]  transpile finished in 2.53 s
[35:49.7]  copy started ...
[35:49.7]  generate lazy started ...
[35:49.7]  copy finished (0 files) in 71 ms
[35:50.6]  generate lazy finished in 888 ms
[35:50.6]  build finished, watching for changes... in 3.47 s
```
Everything works fine.

This simple repro only demonstrates the issue in `globalStyle`, however it affects component `scss` files as well.

This is also an issue in Stencil 2, but I kept it on Stencil 1 because `@stencil/sass` v1.3.2 doesn't support Stencil 2 and I wanted to keep the changes between scenarios to a minimum.

### PR DESCRIPTION
**Pull request by SheepFromHeaven**
Fixes #43

### CODE REVIEW

**Comment by SheepFromHeaven** [comment]
Ouh, tests failing. Will fix.

**Comment by SheepFromHeaven** [comment]
Tests fixed

**Comment by dutscher** [comment]
+1 and i debugged this now aswell :D thanks for the fix!

**Comment by splitinfinities** [comment]
Hey folks! I'd like to figure out how to get this in, if it's still needed. The only thing I need to understand is what all I can do to get this branch back up to spec with the new history on the main branch. Can y'all do that for me? I'd love to keep your authorship so that you can be marked as a contributor!

**Pull request closed without merging**
